### ISSUE TITLE
Put API keys in vault

### ISSUE THREAD

**Issue by SanderVanhove** [waylayio/Sensors#16]
Some sensors make use of API keys or other confidential information, these can be best put in vault instead of in the `globalSettings` or directly in the sensor's properties itself. At the moment vault gets used by no sensors.

A quick `grep` shows that at least these sensors make use of variable called `api_?key`:

*  [ ] bitcoinGetPrice
*  [ ] isURLAlive
*  [ ] humidity
*  [ ] temperatureRange
*  [ ] isDayOrNight
*  [ ] geoFence
*  [ ] Airvisual
*  [ ] pingNodeServer
*  [ ] currencyLayerExchangeRate
*  [ ] aggregateResources
*  [ ] currentWeather
*  [ ] mongolabGetItem
*  [ ] getResourceByTag
*  [ ] pingWaylayEngine
*  [ ] temperature
*  [ ] sentiment
*  [ ] getGeoFenceListForType
*  [ ] wetWeatherForecast5Days

But of course this sensitive information could also be called differently. We should set the right example and put sensitive information into vault as tenants will look to our sensors for inspiration in creating their own.

**Comment by gillesdemey** [comment]
I think a lot of the plugs could use some TLC, this seems like a good first step 👍

**Comment by francisdb** [comment]
I still think they should fall back in case vault is not available

**Comment by SanderVanhove** [comment]
We could do that, but where do we fallback to? Falling back to global settings would defeat the purpose of using vault.

**Comment by francisdb** [comment]
Why? If you don't put anything in global settings they will fail.

**Comment by SanderVanhove** [comment]
Because vault is supposed to be more secure than global settings.

**Comment by francisdb** [comment]
But if we ever do edge installations there probably won't be any vault available. I see no problem in a fallback to a less secure solution, it's up to the user to choose which one to use.

**Comment by SanderVanhove** [comment]
Ok, yeah that is true, should this be something the user needs to account for in their implementation of the sensor. Or should we provide a function in `waylay(Utils)` that does this fallback automatically?

**Comment by francisdb** [comment]
We should probably try to make this as simple as possible for the user, so fallback + error if not found indicating what was tried

**Comment by SanderVanhove** [comment]
Where do I best add an issue for this? I don't directly find where `waylayUtils` is defined.

**Comment by francisdb** [comment]
https://github.com/waylayio/sandbox-util

**Comment by Antondj5** [comment]
This Issue isn't relevant any-more since we updated all sensors to use declerative binding to fetch the keys.
