### ISSUE TITLE
Evaluate js code to boolean sensor

### ISSUE THREAD

**Issue by francisdb** [waylayio/Sensors#34]
For simple things like taking the maximum of a array value, eg `Math.max($${nodex.rawData.resultArray})`

This came up on slack:

> I think allowing the custom functions to be executed with primitive values and arrays would already do alot?
> This is an example of error by passing an array to the max function w/ declarative binding:
> 65e3b289d572 WARN  Node Function_1[Function:1.0.1] execution failed: [Could not parse formula: [<max([0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0])>] Failed to parse: Expected (anythingButTagStart | variableExpr | end-of-input):1:1, found "<max([0,0,"] internalState = {"lastExecution":"2021-09-10T09:10:00.383458Z","prevValues":{},"statisticalSampleValues":{},"statisticalWindowValues":{},"counterValues":{},"counterWindowValues":{},"sequenceValues":{}}
> 
> francisdb:scala:  11:33 AM
> well, max() is no meant for this use case, it keeps track of the maximum of a single value over time (or n samples over time, or sampled over a time span) (edited) 
> 11:34 but I do agree that this is not very intuitive, this could be a separate sensor for these in-memory aggregations
> 11:35 do we not have a “evaluate js code to number with state thresholds sensor”?
> 
> Anton  11:39 AM
> no we don’t have a sensor like that, but would be a good addition I guess?

**Comment by Ward6548** [comment]
The threshold part should not be included. We decided that sensors should do only 1 thing. If you want a conditional check after that, just chain it with the Condition sensor.

**Comment by Antondj5** [comment]
We already have a sensor that does this, check out the Condition sensor.
