### ISSUE TITLE
getMetricValue should not support duration PT1D but should use P1D

### ISSUE THREAD

**Issue by tovleeuw** [waylayio/Sensors#37]
> T is the time designator that precedes the time components of the representation. 
https://en.wikipedia.org/wiki/ISO_8601#Durations

![image](https://user-images.githubusercontent.com/38496857/143585372-2448b74d-0c13-4e31-b2a5-64cba168cfab.png)

versus

![image](https://user-images.githubusercontent.com/38496857/143585698-cf1c0e6d-093c-42b3-9ae2-922e72581bde.png)

The current sensor implementation should be updated with a new version such that the ENUM list for duration includes PT24H and  no longer includes PT1D

**Comment by francisdb** [comment]
An other improvement would be that the broker 400 errors are be returned instead of the generic overwhelming http error.

**Comment by tovleeuw** [comment]
agreed with Francis. This is even more important for the other getMetric... sensors

**Comment by francisdb** [comment]
Main issue already fixed by @pizuricv, but he should probably have increased the version number to not keep this broken on installations where this plugin exists?
https://github.com/waylayio/Sensors/commit/d1559be55eec833eb6c74c351cf6cd3d138a613c

**Comment by pizuricv** [comment]
That on is already fixed. In the new console, there will be PATCH calls to change these things, I don't believe that this one required version bump. Need to check with @CedricVanhaverbeke

**Comment by francisdb** [comment]
At least in the pas we considered plugins and metdata to be cacheable forever. (considered immutable)
Therefore any change that does not come with a new version is not guaranteed to applied.
